"""Generate supabase/seed_demo.sql: a synthetic, deterministic demo dataset.

Run from the repo root:  python scripts/make_demo_seed.py
"""
import json
import pathlib
import random
from datetime import date, timedelta

ROOT = pathlib.Path(__file__).parent.parent


def build_demo_health_data(days=120, end=date(2026, 9, 30), seed=42):
    rng = random.Random(seed)
    daily = {}
    for i in range(days):
        key = (end - timedelta(days=days - 1 - i)).isoformat()
        daily[key] = {
            "date": key,
            "steps": int(min(25000, max(1500, rng.gauss(8000, 2200)))),
            "resting_hr": round(min(80, max(48, rng.gauss(61, 3))), 1),
            "hrv": round(min(100, max(20, rng.gauss(48, 8))), 1),
            "sleep_hours": round(min(10, max(4, rng.gauss(7.1, 0.9))), 2),
            "active_calories": int(max(100, rng.gauss(420, 90))),
            "exercise_minutes": int(max(0, rng.gauss(35, 15))),
            "spo2": round(min(100, max(94, rng.gauss(97.5, 0.6))), 1),
        }

    rows = list(daily.values())

    def avg(field):
        return sum(r[field] for r in rows) / len(rows)

    summary = {
        "avg_steps": round(avg("steps")),
        "avg_sleep_hours": round(avg("sleep_hours"), 1),
        "avg_resting_hr": round(avg("resting_hr"), 1),
        "avg_hrv": round(avg("hrv"), 1),
        "best_sleep": max(r["sleep_hours"] for r in rows),
        "worst_sleep": min(r["sleep_hours"] for r in rows),
        "best_steps_day": max(rows, key=lambda r: r["steps"])["date"],
        "total_days": len(rows),
    }
    exam_start = end - timedelta(days=20)
    events = [
        {
            "label": "Sample exam week",
            "start": exam_start.isoformat(),
            "end": (exam_start + timedelta(days=6)).isoformat(),
            "color": "#ef4444",
            "icon": "books",
        }
    ]
    return {
        "daily": daily,
        "summary": summary,
        "events": events,
        "generated_at": "2026-09-30T00:00:00",
    }


def build_seed_sql(data):
    payload = json.dumps(data, separators=(",", ":")).replace("'", "''")
    return (
        "-- Synthetic demo data. Generated by scripts/make_demo_seed.py; do not edit by hand.\n"
        "insert into public.health_data (is_demo, data)\n"
        f"values (true, '{payload}'::jsonb)\n"
        "on conflict (is_demo) where is_demo do update\n"
        "  set data = excluded.data, updated_at = now();\n"
    )


if __name__ == "__main__":
    out = ROOT / "supabase" / "seed_demo.sql"
    out.write_text(build_seed_sql(build_demo_health_data()), encoding="utf-8")
    print(f"Wrote {out}")
